// All functions here are browser-only (jsPDF touches the canvas/DOM APIs),
// so they must only ever be called from 'use client' components, and we
// dynamically import('jspdf') so it's never pulled into server bundles.

const NAVY = [15, 28, 63];
const GOLD = [198, 154, 62];
const MUTED = [107, 114, 128];

function addHeader(doc, title) {
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, 210, 32, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont(undefined, 'bold');
  doc.text('Legal Thread BD', 14, 15);
  doc.setFontSize(10);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(...GOLD);
  doc.text(title, 14, 23);
  doc.setTextColor(0, 0, 0);
}

function addFooter(doc) {
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(...MUTED);
  doc.text(
    `Generated by Legal Thread BD on ${new Date().toLocaleString()}`,
    14,
    pageHeight - 10
  );
}

function addRow(doc, y, label, value) {
  doc.setFont(undefined, 'bold');
  doc.setFontSize(11);
  doc.setTextColor(...NAVY);
  doc.text(label, 14, y);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(30, 30, 30);
  const lines = doc.splitTextToSize(String(value ?? '—'), 130);
  doc.text(lines, 65, y);
  return y + Math.max(8, lines.length * 6);
}

function safeName(str) {
  return String(str || 'file').replace(/[^a-z0-9]+/gi, '_').replace(/^_+|_+$/g, '');
}

export async function downloadLawyerProfilePdf(lawyer) {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF();

  addHeader(doc, 'Lawyer Profile');

  let y = 46;
  doc.setFontSize(16);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(...NAVY);
  doc.text(lawyer.name || '', 14, y);
  y += 8;
  doc.setFontSize(11);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(...GOLD);
  doc.text(lawyer.expertise || '', 14, y);
  y += 12;

  doc.setDrawColor(230, 230, 230);
  doc.line(14, y, 196, y);
  y += 10;

  y = addRow(doc, y, 'Practice Area', lawyer.category_name);
  y = addRow(doc, y, 'Experience', `${lawyer.experience_years || 0}+ years`);
  y = addRow(doc, y, 'District', lawyer.district);
  y = addRow(doc, y, 'Address', lawyer.address);
  y = addRow(doc, y, 'Bar Council ID', lawyer.bar_council_id);
  y = addRow(doc, y, 'Consultation Fee', `৳${Number(lawyer.consultation_fee || 0).toFixed(0)}`);
  y = addRow(doc, y, 'Rating', lawyer.rating ? `★ ${Number(lawyer.rating).toFixed(1)}` : '—');
  y = addRow(doc, y, 'Verified', lawyer.is_verified ? 'Yes' : 'No');

  y += 4;
  doc.setDrawColor(230, 230, 230);
  doc.line(14, y, 196, y);
  y += 10;

  doc.setFont(undefined, 'bold');
  doc.setFontSize(11);
  doc.setTextColor(...NAVY);
  doc.text('Bio', 14, y);
  y += 7;
  doc.setFont(undefined, 'normal');
  doc.setFontSize(10.5);
  doc.setTextColor(30, 30, 30);
  const bioLines = doc.splitTextToSize(lawyer.bio || 'No bio provided.', 182);
  doc.text(bioLines, 14, y);

  addFooter(doc);
  doc.save(`${safeName(lawyer.name)}_Profile.pdf`);
}

export async function downloadDocumentPdf(document_) {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF();

  addHeader(doc, 'Legal Document');

  let y = 48;
  doc.setFontSize(15);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(...NAVY);
  const titleLines = doc.splitTextToSize(document_.title || '', 182);
  doc.text(titleLines, 14, y);
  y += titleLines.length * 8 + 4;

  doc.setFontSize(10);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(...GOLD);
  doc.text(`Category: ${document_.category_name || 'General'}`, 14, y);
  y += 12;

  doc.setDrawColor(230, 230, 230);
  doc.line(14, y, 196, y);
  y += 10;

  doc.setFont(undefined, 'bold');
  doc.setFontSize(11);
  doc.setTextColor(...NAVY);
  doc.text('Summary', 14, y);
  y += 7;
  doc.setFont(undefined, 'normal');
  doc.setFontSize(10.5);
  doc.setTextColor(30, 30, 30);
  const descLines = doc.splitTextToSize(document_.description || 'No description available.', 182);
  doc.text(descLines, 14, y);
  y += descLines.length * 6 + 10;

  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  doc.text(
    'This is a summary reference generated by Legal Thread BD. For the full legal text, please consult the official government gazette or a qualified lawyer.',
    14,
    y,
    { maxWidth: 182 }
  );

  addFooter(doc);
  doc.save(`${safeName(document_.title)}.pdf`);
}

export async function downloadAppointmentPdf(appt) {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF();

  addHeader(doc, 'Appointment Confirmation');

  let y = 48;
  doc.setFontSize(14);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(...NAVY);
  doc.text(`Appointment #${appt.id}`, 14, y);
  y += 12;

  doc.setDrawColor(230, 230, 230);
  doc.line(14, y, 196, y);
  y += 10;

  y = addRow(doc, y, 'Lawyer', appt.lawyer_name);
  y = addRow(doc, y, 'Expertise', appt.expertise);
  y = addRow(doc, y, 'Client', appt.client_name || appt.user_name);
  y = addRow(doc, y, 'Mode', appt.mode === 'offline' ? 'Offline (in person)' : 'Online');
  y = addRow(
    doc,
    y,
    'Date & Time',
    `${new Date(appt.appointment_date).toLocaleDateString()} at ${appt.appointment_time}`
  );
  y = addRow(doc, y, 'Status', String(appt.status || '').replace('_', ' '));
  if (appt.consultation_fee) {
    y = addRow(doc, y, 'Consultation Fee', `৳${Number(appt.consultation_fee).toFixed(0)}`);
  }
  if (appt.notes) {
    y = addRow(doc, y, 'Notes', appt.notes);
  }

  y += 4;
  doc.setDrawColor(230, 230, 230);
  doc.line(14, y, 196, y);
  y += 10;

  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  doc.text(
    'Please keep this confirmation for your records. Bring a copy to your appointment if it is offline.',
    14,
    y,
    { maxWidth: 182 }
  );

  addFooter(doc);
  doc.save(`Appointment_${appt.id}_${safeName(appt.lawyer_name)}.pdf`);
}
